export const LOAD_PEOPLE_DETAILS = 'LOAD_PEOPLE_DETAILS';
export const LOAD_PEOPLE_DETAILS_SUCCESS = 'LOAD_PEOPLE_DETAILS_SUCCESS';
export const LOAD_PEOPLE_DETAILS_FAILED = 'LOAD_PEOPLE_DETAILS_FAILED';
